### ISSUE TITLE
Displaying "keys" instead of "values" from translation files

### ISSUE THREAD

**Issue by saroshali4** [Ghost-die/ckeditor#1]
I changed the language to "en-gb" in the config file. Now, it shows the keys from the translation file  instead of value.

![image](https://user-images.githubusercontent.com/21079476/79927750-9caf7180-8438-11ea-987d-604102ef5615.png)

Any suggestions please?

**Comment by ghost-die** [comment]
Thanks for your help, the problem has been fixed, please update

**Comment by saroshali4** [comment]
> Thanks for your help, the problem has been fixed, please update

Wonderful, it's working now.
